-- CREATE DATABASE IF NOT EXISTS `test`;

CREATE USER test WITH PASSWORD 'test' CREATEDB;
CREATE DATABASE test
    WITH 
    OWNER = test
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
GRANT ALL ON `test`.* TO 'user'@'%';

CREATE TABLE `LARI_CLUSTER_CONFIGURATIONS` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `CLUSTER_ID` bigint(20) unsigned NOT NULL,
  `CONFIG_TYPE` VARCHAR(45) NOT NULL COMMENT '설정 종류',
  `CONFIG_LOAD_STATUS` VARCHAR(45) NOT NULL COMMENT '설정 로딩 상태',
  `CONFIG_YAML` mediumtext DEFAULT NULL COMMENT '설정 yaml',
  `CONFIG_YAML_NOT_APPLIED` mediumtext DEFAULT NULL COMMENT '사용자가 편집해서 아직 반영되지 않은 설정 yaml',
  `CONFIG_YAML_TEST_LOG` VARCHAR(2000) NULL COMMENT '설정 파일 테스트 결과',
  `CREATED_AT` timestamp NULL DEFAULT current_timestamp(),
  `UPDATED_AT` timestamp NULL DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  `UPDATED_BY` varchar(45) DEFAULT NULL,
  `IS_DELETED` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사용자 클러스터의 설정 정보 테이블';