swagger: '2.0'
info:
  description: 'This is nodejs portal nexclipper api.'
  version: '1.0.0'
  title: 'Swagger nexclipper'
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: 'apiteam@swagger.io'
host: 'nexclipper.io'
basePath: '/'
tags:
  - name: tableId
    description: tableId API

paths:
  # [GET] tableId/tableName
  /tableId/{tableName}:
    get:
      tags:
        - tableId
      summary: issue TableId by tableName
      parameters:
        - name: tableName
          in: path
          description: tableName
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        404:
          description: 'Missing Table Metadata'
        500:
          description: 'Server Error'

