variables:
  DOCKER_DRIVER: overlay
  APP_DOCKERFILE_LOCATION: "Dockerfile"
  APP_IMAGE_NAME: "nexclipper-node"

default:
  services:
    - docker:dind
  tags:
    - nexclipper
  retry: 2
  image: docker:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build
  - package
  - deploy-dev

node-build:
  image: node:lts-alpine
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - package-lock.json
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/


docker-build:
  stage: package
  before_script:
    - "apk add --no-cache git"
  script:
    - echo "building docker image for $APP_IMAGE_NAME "
    - "source kube/build.sh $APP_IMAGE_NAME"
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/

deploy-nexclipper-frontend:
  stage: deploy-dev
  image: dtzar/helm-kubectl:latest
  before_script:
    - echo -e "\nLogin to Kubernetes"
    - source /data/scripts/login-cluster.sh dev
  script:
    - "source kube/deploy.sh node"
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/
      when: manual
