version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'

    volumes:
        - ./init:/docker-entrypoint-initdb.d

  node:
    image: nexcliper-node:local
    restart: always
    container_name: nexclipper-node
    env_file:
      - .env.sample.local
    ports:
      - 5001:5001

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
