apiVersion: v1
kind: Namespace
metadata:
  name:  nc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  ${APP_IMAGE_NAME}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_IMAGE_NAME}-configmap
  labels:
    app: ${APP_IMAGE_NAME}
data:
  # need to add data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_IMAGE_NAME}
spec:
  revisionHistory
  : 0 # Default to 10 if not specified
  selector:
    matchLabels:
      app: ${APP_IMAGE_NAME}
  template:
    metadata:
      labels:
        app: ${APP_IMAGE_NAME}
    spec:
      containers:
        - name: ${APP_IMAGE_NAME}
          image: ${IMG_TAG_TO_DEPLOY}
          imagePullPolicy: Always
          resources:
            limits:
              memory: 2024Mi
            requests:
              cpu: 250m
              memory: 512Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1002
            capabilities:
              drop:
                - SETUID
                - SETGID
          livenessProbe:
            tcpSocket:
              port: 7001
            initialDelaySeconds: 90
            timeoutSeconds: 15
          volumeMounts:
            - name:  varlog
              mountPath:  /var/log
          envFrom:
            - configMapRef:
                name: ${APP_IMAGE_NAME}-configmap
          env:
            - name: NC_LARI_DB_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ncdb-mariadb
                  key: mariadb-root-password
          ports:
            - containerPort: 7001
      volumes:
        - name: varlog
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_IMAGE_NAME}
  labels:
    app: ${APP_IMAGE_NAME}
spec:
  selector:
    app: ${APP_IMAGE_NAME}
  ports:
    - port: 5001
      targetPort: 5001
      name: http
    - port: 5002
      targetPort: 5002
      name: metric

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ${APP_IMAGE_NAME}
  labels:
    app: ${APP_IMAGE_NAME}
spec:
  selector:
    matchLabels:
      app: ${APP_IMAGE_NAME}
  namespaceSelector:
    matchNames:
      - nc
  endpoints:
    - honorLabels: true
      path: /metrics
      scrapeTimeout: 30s
      interval: 30s
      port: metric
