apiVersion: v1
kind: Namespace
metadata:
  name:  nc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  ${APP_IMAGE_NAME}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_IMAGE_NAME}-configmap
  labels:
    app: ${APP_IMAGE_NAME}
data:
  NC_LARI_PORT: "5001"
  NC_LARI_URL: "http://nexclipper-api.nc.svc.cluster.local"
  NC_LARI_ENV: development
  NC_LARI_DB_CONFIG_PORT: "3306"
  NC_LARI_DB_CONFIG_HOST: "ncdb-mariadb-primary.mariadb.svc.cluster.local"
  NC_LARI_DB_CONFIG_USER: "root"
  NC_LARI_DB_CONFIG_DB_NAME: nc_api
  NC_LARI_DB_CONFIG_POOL_MIN: "1"
  NC_LARI_DB_CONFIG_POOL_MAX: "5"
  NC_LARI_EMAIL_DEFAULT_FROM: info@nexclipper.io
  NC_LARI_MAILGUN_DOMAIN: mg.nexclipper.io
  NC_LARI_SOCIALKEY_GOOGLE_CLIENT_ID: "1234"
  NC_LARI_SOCIALKEY_GOOGLE_CLIENT_SECRET: "1234"
  NC_LARI_SOCIALKEY_GOOGLE_CALLBACK_URL: ""
  NC_LARI_SOCIALKEY_GITHUB_CLIENT_ID: "1234"
  NC_LARI_SOCIALKEY_GITHUB_CLIENT_SECRET: "1234"
  NC_LARI_SOCIALKEY_GITHUB_CALLBACK_URL: ""
  NC_LARI_JWT_SECRET_KEY: "test123!"
  NC_LARI_LOG_FORMAT: combined
  NC_LARI_CORS_ORIGIN: "true"
  NC_LARI_CORS_CREDENTIALS: "true"
  NC_LARI_EMAIL_PASSWORD_RESET_PAGE_URL: http://nexclipper-api:5001/reset
  NC_LARI_EMAIL_VERIFICATION_PAGE_URL: http://nexclipper-api:5001/verify
  NC_LARI_SYSTEM_NAME: SYSTEM
  NC_LARI_SYSTEM_CUSTOMERACCOUNT_NAME: NEXCLIPPER_INC
  NC_LARI_SYSTEM_CUSTOMERACCOUNT_DESCRIPTION: Internal_Account
  NC_LARI_SYSTEM_PARTY_NAME: SYSTEM
  NC_LARI_SYSTEM_PARTY_DESCRIPTION: Internal_Account_User
  NC_LARI_SYSTEM_PARTYUSER_FIRSTNAME: SYSTEM
  NC_LARI_SYSTEM_PARTYUSER_LASTNAME: EXECUTOR
  NC_LARI_SYSTEM_PARTYUSER_USERID: system@nexclipper.io
  NC_LARI_SYSTEM_PARTYUSER_PASSWORD: Password@123!
  NC_LARI_SYSTEM_PARTYUSER_EMAIL: system@nexclipper.io
  SUDORY_X_AUTH_TOKEN: "SUDORY"
  SUDORY_BASE_URL: "http://144.126.243.14:8099"
  SUDORY_PATH_CREATECLUSTER: "/server/cluster"
  SUDORY_PATH_CREATETOKEN: "/server/cluster_token"
  SUDORY_PATH_SESSION: "/server/session"
  SUDORY_PATH_SERVICE: "/server/service"
  SUDORY_SUBSCRIBED_CHANNEL_RESOURCE: "0e81d1f1fb224485877374d1d9038d0d"
  SUDORY_SUBSCRIBED_CHANNEL_ALERT: "a97f377b443b42b9844ff1c2ecb41b5f"
  SUDORY_SUBSCRIBED_CHANNEL_METRIC: "25ec71142ced4841a4fe8e09a17c0dc0"
  SUDORY_SUBSCRIBED_CHANNEL_METRIC_RECEIVED: "2aaf5c9266084237b91494c4fb99adae"
  SUDORY_SERVICE_RESULT_DELETE: "1"
  SUDORY_REPO_NAME: "nex"
  SUDORY_REPO_URL: "https://repo.nexclipper.io/chartrepo/nexclipper"
  NC_CRON_URL: "http://nexclipper-cron.nc.svc.cluster.local:5001"
  NC_CRON_X_AUTH_TOKEN: "CRON"
  NC_LARI_MONGO_URL: "mongodb://nc_api:nc_api@ncmongodb.mongodb.svc.cluster.local:27017/nc_api"
  NC_LARI_VM_ADDRESS: "http://vm-victoria-metrics-single-server.vm.svc.cluster.local:8428"
  NC_LARI_VM_API: "/api/v1/import?extra_label=clusterUuid="
  NC_LARI_DO_BUCKET: "nc-api-storage"
  NC_LARI_DO_DEFAULT_REGION: "sgp1"
  NC_LARI_DO_ENDPOINT: "https://sgp1.digitaloceanspaces.com"
  NODE_OPTIONS: "--max-old-space-size=8192"
  NC_ALERTHUB_URL: "http://nexclipper-notification.nc.svc.cluster.local:3039"
  NC_ALERTHUB_X_AUTH_TOKEN: "NC_ALERTHUB"
  SUDORY_SUBSCRIBED_CHANNEL_WEBHOOK: "8f0583fbdb0c4060adc05e80736385f7"
  NC_LARI_RESOURCE_CRON: "* * * * *"
  NC_LARI_ALERT_CRON: "* * * * *"
  NC_LARI_METRIC_CRON: "*/5 * * * *"
  NC_LARI_METRICOPS_CRON: "*/2 * * * *"
  NC_LARI_HEALTH_CRON: "*/5 * * * *"
  NC_LARI_METRIC_RECEIVED_CRON: "* * * * *"
  NC_BN_URL: "http://nexclipper-bn.nc.svc.cluster.local:3000"
  NC_BN_PREDICT_PATH: "/predict_incident/"
  NC_BN_NODE_THRESHOLD: "0.7"
  NC_BN_POD_THRESHOLD: "0.7"
  NC_BN_PVC_THRESHOLD: "0.7"
  NC_BN_REFRESH_MODEL_PATH: "/refresh_model/"
  NC_TURN_OFF_TELEMETRY: "true"
  NC_LARI_DEFAULT_PASSWORD: "WOt7u7OGxr"
  NC_PROMETHEUS_URL_HEAD: "http://kps-kube-prometheus-stack-prometheus."
  NC_PROMETHEUS_URL_TAIL: ".svc.cluster.local:9090"
  NC_GRAFANA_URL_HEAD: "http://kps-grafana."
  NC_GRAFANA_URL_TAIL: ".svc.cluster.local:80"
  NC_ALERTMANAGER_URL_HEAD: "http://kps-kube-prometheus-stack-alertmanager."
  NC_ALERTMANAGER_URL_TAIL: ".svc.cluster.local:9093"
  NC_LOKI_URL_HEAD: "http://loki."
  NC_LOKI_URL_TAIL: ".svc.cluster.local:3100"
  NC_LARI_LOG_SILENCE_RESPONSE: "true"
  FUSEBILL_BASE_URL: "https://secure.fusebill.com/v1/"
  FUSEBILL_API_CREATE_CUSTOMER_URL: "https://secure.fusebill.com/v1/customers"
  FUSEBILL_API_CANCEL_CUSTOMER_URL: "https://secure.fusebill.com/v1/CustomerCancellation"
  NC_LOKI_API_BASE_URL: "http://loki.monitor.svc.cluster.local:3100/loki/api/v1"
  NC_VM_MULTI_BASE_URL_INSERT: "http://vm-cluster-victoria-metrics-cluster-vminsert.vm-multi-tenant.svc.cluster.local:8480/insert"
  NC_VM_MULTI_BASE_URL_SELECT: "http://vm-cluster-victoria-metrics-cluster-vmselect.vm-multi-tenant.svc.cluster.local:8481/select"
  NC_VM_MULTI_AUTH_URL: "http://vm-auth-victoria-metrics-auth.vm-multi-tenant.svc.cluster.local:8427"
  NC_VM_MULTI_NAMESPACE: "vm-multi-tenant"
  NC_VM_MULTI_SECRET: "vm-auth-victoria-metrics-auth"
  NC_VM_MULTI_CLUSTER_UUID: "89fa971849114f1c96a2e2deac19db94"
  NC_VM_OPTION: "SINGLE"
  NC_METRIC_RECEIVED_SWITCH: "on"
  NODE_APP_INSTANCE: "nc-api"
  NC_API_METRIC_PORT: "5002"
  NC_API_CLUSTER_OUTAGE_DECISION_MIN: "5"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_IMAGE_NAME}
spec:
  selector:
    matchLabels:
      app: ${APP_IMAGE_NAME}
  template:
    metadata:
      labels:
        app: ${APP_IMAGE_NAME}
    spec:
      containers:
      - name: ${APP_IMAGE_NAME}
        image: ${IMG_TAG_TO_DEPLOY}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 250m
            memory: 512Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 1002
          capabilities:
            drop:
              - SETUID
              - SETGID
        livenessProbe:
          tcpSocket:
            port: 5001
          initialDelaySeconds: 90
          timeoutSeconds: 15
        volumeMounts:
          - name:  varlog
            mountPath:  /var/log
        envFrom:
          - configMapRef:
              name: ${APP_IMAGE_NAME}-configmap
        env:
          - name: NC_LARI_DB_CONFIG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ncdb-mariadb
                key: mariadb-root-password
          - name: NC_LARI_DO_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: nc-do-keys
                key: do-access-key
          - name: NC_LARI_DO_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: nc-do-keys
                key: do-secret-key
          - name: NC_LARI_MAILGUN_API_KEY
            valueFrom:
              secretKeyRef:
                name: nc-mailgun-apikey
                key: apiKey
          - name: FUSEBILL_API_KEY
            valueFrom:
              secretKeyRef:
                name: nc-fusebill-apikey
                key: apiKey
        ports:
        - containerPort: 5001
        - containerPort: 5002
      volumes:
        - name: varlog
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_IMAGE_NAME}
  labels:
    app: ${APP_IMAGE_NAME}
spec:
  selector:
    app: ${APP_IMAGE_NAME}
  ports:
  - port: 5001
    targetPort: 5001
    name: http
  - port: 5002
    targetPort: 5002
    name: metric

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ${APP_IMAGE_NAME}
  labels:
    app: ${APP_IMAGE_NAME}
spec:
  selector:
    matchLabels:
      app: ${APP_IMAGE_NAME}
  namespaceSelector:
    matchNames:
    - nc
  endpoints:
  - honorLabels: true
    path: /metrics
    scrapeTimeout: 30s
    interval: 30s
    port: metric
