apiVersion: v1
kind: Namespace
metadata:
  name:  nc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  ${APP_IMAGE_NAME}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_IMAGE_NAME}-configmap
  labels:
    app: ${APP_IMAGE_NAME}
data:
  CO_AGGREGATOR_DB_CONFIG_PORT: "3306"
  CO_AGGREGATOR_DB_CONFIG_HOST: "olly-dev-db.claion.io"
  CO_AGGREGATOR_DB_CONFIG_USER: "root"
  CO_AGGREGATOR_DB_CONFIG_PASSWORD: "gu7C89wD8X"
  CO_AGGREGATOR_DB_CONFIG_DB_NAME: "nc_api"
  CO_AGGREGATOR_DB_CONFIG_POOL_MIN: "1"
  CO_AGGREGATOR_DB_CONFIG_POOL_MAX: "5"
  CO_AGGREGATOR_DEFAULT_PASSWORD: "WOt7u7OGxr"
  CO_AGGREGATOR_SYSTEM_NAME: "SYSTEM"
  CO_AGGREGATOR_SYSTEM_CUSTOMERACCOUNT_NAME: "CLAION"
  CO_AGGREGATOR_SYSTEM_CUSTOMERACCOUNT_DESCRIPTION: "Internal_Account"
  CO_AGGREGATOR_SYSTEM_PARTY_NAME: "SYSTEM"
  CO_AGGREGATOR_SYSTEM_PARTY_DESCRIPTION: "Internal_Account_User"
  CO_AGGREGATOR_SYSTEM_PARTYUSER_FIRSTNAME: "SYSTEM"
  CO_AGGREGATOR_SYSTEM_PARTYUSER_LASTNAME: "EXECUTOR"
  CO_AGGREGATOR_SYSTEM_PARTYUSER_USERID: "system@claion.io"
  CO_AGGREGATOR_SYSTEM_PARTYUSER_PASSWORD: "Password@123!"
  CO_AGGREGATOR_SYSTEM_PARTYUSER_EMAIL: "system@claion.io"
  CO_AGGREGATOR_VM_SINGLE_ADDRESS: "http://olly-dev-vm.claion.io:8428"
  CO_AGGREGATOR_VM_MULTI_ADDRESS: "http://olly-dev-vm.claion.io:8428"
  CO_AGGREGATOR_VM_IMPORT: "/api/v1/import?extra_label: clusterUuid:"
  CO_AGGREGATOR_VM_OPTION: "SINGLE"
  CO_AGGREGATOR_JWT_SECRET_KEY: "test123!"
  CO_AGGREGATOR_LOG_FORMAT: "combined"
  CO_AGGREGATOR_CORS_ORIGIN: "true"
  CO_AGGREGATOR_CORS_CREDENTIALS: "true"
  CO_TURN_OFF_TELEMETRY: "true"
  CO_AGGREGATOR_LOG_SILENCE_RESPONSE: "true"
  CO_PAGINATION_LIMIT: 10
  CO_PAGINATION_PAGE: 0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_IMAGE_NAME}
spec:
  revisionHistoryLimit: 0 # Default to 10 if not specified
  selector:
    matchLabels:
      app: ${APP_IMAGE_NAME}
  template:
    metadata:
      labels:
        app: ${APP_IMAGE_NAME}
    spec:
      containers:
        - name: ${APP_IMAGE_NAME}
          image: ${IMG_TAG_TO_DEPLOY}
          imagePullPolicy: Always
          resources:
            limits:
              memory: 2024Mi
            requests:
              cpu: 250m
              memory: 512Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1002
            capabilities:
              drop:
                - SETUID
                - SETGID
          livenessProbe:
            tcpSocket:
              port: 7001
            initialDelaySeconds: 90
            timeoutSeconds: 15
          volumeMounts:
            - name:  varlog
              mountPath:  /var/log
          envFrom:
            - configMapRef:
                name: ${APP_IMAGE_NAME}-configmap
          ports:
            - containerPort: 7001
      volumes:
        - name: varlog
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_IMAGE_NAME}
  labels:
    app: ${APP_IMAGE_NAME}
spec:
  selector:
    app: ${APP_IMAGE_NAME}
  ports:
    - port: 6001
      targetPort: 6001
      name: http
