apiVersion: v1
kind: Namespace
metadata:
  name:  nc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  ${APP_IMAGE_NAME}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_IMAGE_NAME}-configmap
  labels:
    app: ${APP_IMAGE_NAME}
data:
  CM_DB_CONFIG_PORT: "3306"
  CM_DB_CONFIG_HOST: "localhost"
  CM_DB_CONFIG_USER: "root"
  CM_DB_CONFIG_PASSWORD: "gu7C89wD8X"
  CM_DB_CONFIG_DB_NAME: "carrot_api"
  CM_DB_CONFIG_POOL_MIN: "1"
  CM_DB_CONFIG_POOL_MAX: "5"
  CM_DEFAULT_PASSWORD: "WOt7u7OGxr"
  CM_SYSTEM_NAME: "SYSTEM"
  CM_SYSTEM_CUSTOMERACCOUNT_NAME: "CARROT"
  CM_SYSTEM_CUSTOMERACCOUNT_DESCRIPTION: "Internal_Account"
  CM_SYSTEM_PARTY_NAME: "SYSTEM"
  CM_SYSTEM_PARTY_DESCRIPTION: "Internal_Account_User"
  CM_SYSTEM_PARTYUSER_FIRSTNAME: "SYSTEM"
  CM_SYSTEM_PARTYUSER_LASTNAME: "EXECUTOR"
  CM_SYSTEM_PARTYUSER_USERID: "jeongcm0101@gmail.com"
  CM_SYSTEM_PARTYUSER_PASSWORD: "123"
  CM_SYSTEM_PARTYUSER_EMAIL: "jeongcm0101@gmail.com"
  CM_VM_SINGLE_ADDRESS: "http://localhost:8428"
  CM_VM_MULTI_ADDRESS: "http://localhost:8427"
  CM_VM_IMPORT: "/api/v1/import?extra_label=clusterUuid="
  CM_VM_OPTION: "SINGLE"
  CM_JWT_SECRET_KEY: "test123!"
  CM_LOG_FORMAT: "combined"
  CM_CORS_ORIGIN: "true"
  CM_CORS_CREDENTIALS: "true"
  CM_EXPORTER_TURN_OFF_TELEMETRY: "true"
  CM_LOG_SILENCE_RESPONSE: "true"
  CM_EXPORTER_PAGINATION_LIMIT: "10"
  CM_EXPORTER_PAGINATION_PAGE: "0"
  CM_EXPORTER_API_URL: "http://localhost"
  CM_EXPORTER_API_PORT: "5001"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_IMAGE_NAME}
spec:
  revisionHistoryLimit: 0 # Default to 10 if not specified
  selector:
    matchLabels:
      app: ${APP_IMAGE_NAME}
  template:
    metadata:
      labels:
        app: ${APP_IMAGE_NAME}
    spec:
      containers:
        - name: ${APP_IMAGE_NAME}
          image: ${IMG_TAG_TO_DEPLOY}
          imagePullPolicy: Always
          resources:
            limits:
              memory: 2024Mi
            requests:
              cpu: 250m
              memory: 512Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1002
            capabilities:
              drop:
                - SETUID
                - SETGID
          livenessProbe:
            tcpSocket:
              port: 6001
            initialDelaySeconds: 90
            timeoutSeconds: 15
          volumeMounts:
            - name:  varlog
              mountPath:  /var/log
          envFrom:
            - configMapRef:
                name: ${APP_IMAGE_NAME}-configmap
          ports:
            - containerPort: 6001
      volumes:
        - name: varlog
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_IMAGE_NAME}
  labels:
    app: ${APP_IMAGE_NAME}
spec:
  selector:
    app: ${APP_IMAGE_NAME}
  ports:
    - port: 6001
      targetPort: 6001
      name: http
