apiVersion: v1
kind: Namespace
metadata:
  name:  nc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  ${APP_IMAGE_NAME}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_IMAGE_NAME}-configmap
  labels:
    app: ${APP_IMAGE_NAME}
data:
  NC_LARI_PORT: "5001"
  NC_LARI_URL: "http://nexclipper-api.nc.svc.cluster.local"
  NC_LARI_ENV: development
  NC_LARI_DB_CONFIG_PORT: "3306"
  NC_LARI_DB_CONFIG_HOST: "ncdb.prd.nexclipper.local"
  NC_LARI_DB_CONFIG_DB_NAME: nc_api
  NC_LARI_DB_CONFIG_POOL_MIN: "1"
  NC_LARI_DB_CONFIG_POOL_MAX: "5"
  NC_LARI_EMAIL_DEFAULT_FROM: info@nexclipper.io
  NC_LARI_MAILGUN_API_KEY: ""
  NC_LARI_MAILGUN_DOMAIN: "mg.nexclipper.io"
  NC_LARI_SOCIALKEY_GOOGLE_CLIENT_ID: "1234"
  NC_LARI_SOCIALKEY_GOOGLE_CLIENT_SECRET: "1234"
  NC_LARI_SOCIALKEY_GOOGLE_CALLBACK_URL: ""
  NC_LARI_SOCIALKEY_GITHUB_CLIENT_ID: "1234"
  NC_LARI_SOCIALKEY_GITHUB_CLIENT_SECRET: "1234"
  NC_LARI_SOCIALKEY_GITHUB_CALLBACK_URL: ""
  NC_LARI_JWT_SECRET_KEY: "test123!"
  NC_LARI_LOG_FORMAT: combined
  NC_LARI_CORS_ORIGIN: "true"
  NC_LARI_CORS_CREDENTIALS: "true"
  NC_LARI_EMAIL_PASSWORD_RESET_PAGE_URL: http://nexclipper-api:5001/reset
  NC_LARI_EMAIL_VERIFICATION_PAGE_URL: http://nexclipper-api:5001/verify
  NC_LARI_SYSTEM_NAME: SYSTEM
  NC_LARI_SYSTEM_CUSTOMERACCOUNT_NAME: NEXCLIPPER_INC
  NC_LARI_SYSTEM_CUSTOMERACCOUNT_DESCRIPTION: Internal_Account
  NC_LARI_SYSTEM_PARTY_NAME: SYSTEM
  NC_LARI_SYSTEM_PARTY_DESCRIPTION: Internal_Account_User
  NC_LARI_SYSTEM_PARTYUSER_FIRSTNAME: SYSTEM
  NC_LARI_SYSTEM_PARTYUSER_LASTNAME: EXECUTOR
  NC_LARI_SYSTEM_PARTYUSER_USERID: system@nexclipper.io
  NC_LARI_SYSTEM_PARTYUSER_PASSWORD: Password@123!
  NC_LARI_SYSTEM_PARTYUSER_EMAIL: system@nexclipper.io
  SUDORY_X_AUTH_TOKEN: "SUDORY"
  SUDORY_BASE_URL: "http://a05575fbc8661459ab7d35dc431d3d2e-998310490.eu-central-1.elb.amazonaws.com:8099"
  SUDORY_PATH_CREATECLUSTER: "/server/cluster"
  SUDORY_PATH_CREATETOKEN: "/server/cluster_token"
  SUDORY_PATH_SESSION: "/server/session"
  SUDORY_PATH_SERVICE: "/server/service"
  SUDORY_SUBSCRIBED_CHANNEL_RESOURCE: "be19c211fa1340c498689fee93f386b6"
  SUDORY_SUBSCRIBED_CHANNEL_ALERT: "nc_a3eb4fce4e1b84c109ea34962dbaf6862lert"
  SUDORY_SUBSCRIBED_CHANNEL_METRIC: "7ee1673f7bc14fcf85ea8a518edceb5a"
  SUDORY_SUBSCRIBED_CHANNEL_METRIC_RECEIVED: "44f4a98fa42749688782a6f64bcfcbbd"
  SUDORY_SERVICE_RESULT_DELETE: "1"
  SUDORY_REPO_NAME: "nex-dev"
  SUDORY_REPO_URL: "https://repo.nexclipper.io/chartrepo/nexclipper-dev"
  NC_CRON_URL: "http://nexclipper-cron.nc.svc.cluster.local:5001"
  NC_CRON_X_AUTH_TOKEN: "CRON"
  NC_LARI_VM_ADDRESS: "http://vm-victoria-metrics-single-server.vm.svc.cluster.local:8428"
  NC_LARI_VM_API: "/api/v1/import?extra_label=clusterUuid="
  NC_LARI_DO_BUCKET: "nc-api-prd-storage"
  NC_LARI_DO_DEFAULT_REGION: "sgp1"
  NC_LARI_DO_ENDPOINT: "sgp1.digitaloceanspaces.com"
  NODE_OPTIONS: "--max-old-space-size=8192"
  NC_ALERTHUB_URL: "http://nexclipper-notification.nc.svc.cluster.local:3039"
  NC_ALERTHUB_X_AUTH_TOKEN: "NC_ALERTHUB"
  SUDORY_SUBSCRIBED_CHANNEL_WEBHOOK: "482b889fd74848c9adae018c7a95de85"
  NC_LARI_RESOURCE_CRON: "* * * * *"
  NC_LARI_ALERT_CRON: "* * * * *"
  NC_LARI_METRIC_CRON: "*/5 * * * *"
  NC_LARI_HEALTH_CRON: "*/5 * * * *"
  NC_LARI_METRIC_RECEIVED_CRON: "* * * * *"
  NC_BN_URL: "http://nexclipper-bn.nc.svc.cluster.local:3000"
  NC_BN_NODE_BASE: "/predict_incident/"
  NC_BN_NODE_THRESHOLD: "0.8"
  NC_BN_REFRESH_MODEL_PATH: "/refresh_model/"
  NC_TURN_OFF_TELEMETRY: "true"
  NC_LARI_DEFAULT_PASSWORD: "WOt7u7OGxr"
  NC_PROMETHEUS_URL_HEAD: "http://kps-kube-prometheus-stack-prometheus."
  NC_PROMETHEUS_URL_TAIL: ".svc.cluster.local:9090"
  NC_GRAFANA_URL_HEAD: "http://kps-grafana."
  NC_GRAFANA_URL_TAIL: ".svc.cluster.local:80"
  NC_ALERTMANAGER_URL_HEAD: "http://kps-kube-prometheus-stack-alertmanager."
  NC_ALERTMANAGER_URL_TAIL: ".svc.cluster.local:9093"
  NC_LOKI_URL_HEAD: "http://loki."
  NC_LOKI_URL_TAIL: ".svc.cluster.local:3100"
  NC_LARI_LOG_SILENCE_RESPONSE: "true"


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_IMAGE_NAME}
spec:
  selector:
    matchLabels:
      app: ${APP_IMAGE_NAME}
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: 'nexclipper-app'
        vault.hashicorp.com/agent-inject-secret-ncdb-admin-login: 'kv/database/ncdb'
        vault.hashicorp.com/agent-inject-template-ncdb-admin-login: |
          {{- with secret "kv/database/ncdb" -}}
          NC_LARI_DB_CONFIG_USER={{ .Data.data.username }}
          NC_LARI_DB_CONFIG_PASSWORD={{ .Data.data.password }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-nc-mailgun: 'kv/common/mailgun'
        vault.hashicorp.com/agent-inject-template-nc-mailgun: |
          {{- with secret "kv/common/mailgun" -}}
          NC_LARI_MAILGUN_API_KEY={{ .Data.data.apiKey }}
          {{- end -}}  
      labels:
        app: ${APP_IMAGE_NAME}
    spec:
      serviceAccountName: ${APP_IMAGE_NAME}
      containers:
      - name: ${APP_IMAGE_NAME}
        image: ${IMG_TAG_TO_DEPLOY}
        imagePullPolicy: Always
        resources: {}
        livenessProbe:
          tcpSocket:
            port: 5001
          initialDelaySeconds: 90
          timeoutSeconds: 15
        envFrom:
          - configMapRef:
              name: ${APP_IMAGE_NAME}-configmap
        env:
          - name: NC_LARI_DO_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: nc-do-keys
                key: do-access-key
          - name: NC_LARI_DO_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: nc-do-keys
                key: do-secret-key
          - name: NC_LARI_MAILGUN_API_KEY
            valueFrom:
              secretKeyRef:
                name: nc-mailgun-apikey
                key: apiKey      
      
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_IMAGE_NAME}
spec:
  selector:
    app: ${APP_IMAGE_NAME}
  ports:
  - port: 5001
    targetPort: 5001
